### ISSUE TITLE
Specs failing with Ruby 2.4

### ISSUE THREAD

**Issue by kennyadsl** [nebulab/solidus_page_objects#21]
```bash
> be rspec spec

Randomized with seed 58340
.........F............

Failures:

  1) SolidusPageObjects::Sections::Cart#apply_coupon_code
     Failure/Error: update_button.click

     ArgumentError:
       key must be 32 bytes
     # ./lib/solidus_page_objects/components/cart.rb:19:in `apply_coupon_code'
     # ./spec/solidus_page_objects/sections/cart_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/solidus_page_objects/sections/cart_spec.rb:14:in `block (3 levels) in <top (required)>'

Finished in 49.11 seconds (files took 4.5 seconds to load)
22 examples, 1 failure

Failed examples:

rspec ./spec/solidus_page_objects/sections/cart_spec.rb:14 # SolidusPageObjects::Sections::Cart#apply_coupon_code
```

**Comment by mtylty** [comment]
This should be fixed by now.
